default: &default
  adapter: postgresql
  encoding: unicode
  database: education_platform_mpp_development
  username: postgres
  password: root
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: education_platform_mpp_development
  username: postgres
  password: root
  host: localhost
  port: 5432

test:
  <<: *default
  database: education_platform_mpp_test

production:
  <<: *default
  database: education_platform_mpp_production
  username: education_platform_mpp
  password: <%= ENV["EDUCATION_PLATFORM_MPP_DATABASE_PASSWORD"] %>
